### ISSUE TITLE
Sample code for initializeToken() is wrong?

### ISSUE THREAD

**Issue by roschler** [dolbyio-samples/comms-sdk-web-getting-started#33]
On this page in this repo:

comms-sdk-web-getting-started/src/scripts/client.js

You have this code showing for initializing a token:

```js
    // Initialize the Voxeet SDK
    // Please read the documentation at:
    // https://docs.dolby.io/communications-apis/docs/initializing-javascript
    // Generate a client access token from the Dolby.io dashboard and insert into access_token variable
    let access_token = "ClientAccessToken";
    VoxeetSDK.initializeToken(access_token, (isExpired) => {
      return new Promise((resolve, reject) => {
        if (isExpired) {
          reject('The access token has expired.');
        } else {
          resolve(access_token);
        }
      });
    });
```

However the docs you reference in that code shows this instead:

```js
async function getAccessToken() {
    const url = serverURL + '/api/token';
    // Request an access token from your backend
    const response = await fetch(url);

    // extract the access token
    const json = await response.json();
    return json.access_token;
}

async function initializeSDK() {
    const accessToken = await getAccessToken();

    VoxeetSDK.initializeToken(accessToken, async () => {
        // This callback is called when the token needs to be refreshed.
        return await getAccessToken();
    });
}
```

The docs page concurs with my testing.  The callback is only called when the token is expired, otherwise the callback function is _not_ fired.  Therefore:

1) It any case it is a strange to be returning a promise in that sample code at all inside of the body of the callback function.  It is neither awaited or does it have an attached `then` block.  Is this an error?

2) Either way, since the callback function is only called if the token is expired, the `(isExpired)` argument to the anonymous callback function is superfluous since it should always have a value of `true`.  I did see the callback called when one of my access tokens expired and `isExpired` was indeed `true`.  But as I said, I never saw that callback fire with a valid access token that had not expired et.  

I will go by the code in the docs page instead.

**Comment by roschler** [comment]
Follow-up comment.  It would better, at least for my app, if  there was a function that I could call to initialize the token that did _not_ have a callback and simply failed if the token was invalid.  My app uses its own sessions for each virtual world instance and I don't want to refresh the token if it is expired, because if the world has expired it stays expired ("dead").  Unfortunately, given the current code structure there is no way for me to `await` a result that tells me immediately if the token is invalid or not, so I could avoid running subsequent code that is only supposed to run if the access token is still valid.

Is there a way to simply check if an access token is valid or not?

**Comment by FabienLavocat** [comment]
@roschler you are raising a good point for the code sample, this could have been simplified to:
```js
let access_token = "ClientAccessToken";
VoxeetSDK.initializeToken(access_token, () => new Promise((resolve) => resolve(access_token)));
```

However, the goal of this project and code sample is to demonstrate how a production application should behave and this means that the token needs to eventually be refreshed. If you generate an access token that is valid for 1 hour, then the SDK will attempt to refresh it after 30 minutes and if it fails, try again after 15 minutes.

We don't have a way to check if a token is valid or not, BUT, if it is invalid (forged, malformed...) the SDK will not initialized itself. What you can do however is check when the token expires, here is a [code snippet](https://github.com/dolbyio-samples/comms-sdk-web-sample/blob/main/script.js#L36-L44) for this.

Note that you can simply ignore the `isExpired` flag in the callback, because the SDK should ask to refresh it ahead of time.

**Comment by roschler** [comment]
@FabienLavocat Agreed, that sample is much better!  And thanks for the code snippet.  I'll close the issue as my code is now working properly with token authentication.
